sudo: required
services:
    - docker

before_install:
    - docker build -t nvnrvi/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run nvnrvi/react-test npm test -- --coverage

after_success:
    - docker build -t nvnrvi/multi-client ./client
    - docker build -t nvnrvi/multi-worker ./worker
    - docker build -t nvnrvi/multi-server ./server
    - docker build -t nvnrvi/multi-nginx ./nginx

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push nvnrvi/multi-client
    - docker push nvnrvi/multi-server
    - docker push nvnrvi/multi-worker
    - docker push nvnrvi/multi-nginx